#DEFINE TESTING_NAVTOMLLEXERTOKENIZE
#DEFINE TESTING_NAVTOMLLEXEREDGECASES
#DEFINE TESTING_NAVTOMLPARSE
#DEFINE TESTING_NAVTOMLQUERY
#DEFINE TESTING_NAVTOMLQUERYSTRING
#DEFINE TESTING_NAVTOMLQUERYINTEGER
#DEFINE TESTING_NAVTOMLQUERYSIGNEDINTEGER
#DEFINE TESTING_NAVTOMLQUERYFLOAT
#DEFINE TESTING_NAVTOMLQUERYBOOLEAN
#DEFINE TESTING_NAVTOMLQUERYLONG
#DEFINE TESTING_NAVTOMLQUERYSIGNEDLONG
#DEFINE TESTING_NAVTOMLTYPECHECKING
#DEFINE TESTING_NAVTOMLGETPARENTNODE
#DEFINE TESTING_NAVTOMLTREEINFO
#DEFINE TESTING_NAVTOMLVALIDATION
#DEFINE TESTING_NAVTOMLVALUEGETTERS
#DEFINE TESTING_NAVTOMLQUERYSTRINGARRAY
#DEFINE TESTING_NAVTOMLQUERYINTEGERARRAY
#DEFINE TESTING_NAVTOMLQUERYSIGNEDINTEGERARRAY
#DEFINE TESTING_NAVTOMLQUERYFLOATARRAY
#DEFINE TESTING_NAVTOMLQUERYBOOLEANARRAY
#DEFINE TESTING_NAVTOMLQUERYLONGARRAY
#DEFINE TESTING_NAVTOMLQUERYSIGNEDLONGARRAY
#DEFINE TESTING_NAVTOMLDEEPNESTING
#DEFINE TESTING_NAVTOMLLARGEARRAYS
#DEFINE TESTING_NAVTOMLLIMITS
#DEFINE TESTING_NAVTOMLNAVIGATIONEDGECASES
#DEFINE TESTING_NAVTOMLQUERYEDGECASES
#DEFINE TESTING_NAVTOMLPARSERUNESCAPESTRING
#DEFINE TESTING_NAVTOMLESCAPESEQUENCES
// #DEFINE TOML_LEXER_DEBUG
// #DEFINE TOML_PARSER_DEBUG
// #DEFINE TOML_QUERY_DEBUG
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Toml.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVTOMLLEXERTOKENIZE
#include 'NAVTomlLexerTokenize.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLLEXEREDGECASES
#include 'NAVTomlLexerEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLPARSE
#include 'NAVTomlParse.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERY
#include 'NAVTomlQuery.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYSTRING
#include 'NAVTomlQueryString.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYINTEGER
#include 'NAVTomlQueryInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDINTEGER
#include 'NAVTomlQuerySignedInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYFLOAT
#include 'NAVTomlQueryFloat.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYBOOLEAN
#include 'NAVTomlQueryBoolean.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYLONG
#include 'NAVTomlQueryLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDLONG
#include 'NAVTomlQuerySignedLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLTYPECHECKING
#include 'NAVTomlTypeChecking.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLGETPARENTNODE
#include 'NAVTomlGetParentNode.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYSTRINGARRAY
#include 'NAVTomlQueryStringArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYINTEGERARRAY
#include 'NAVTomlQueryIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDINTEGERARRAY
#include 'NAVTomlQuerySignedIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYFLOATARRAY
#include 'NAVTomlQueryFloatArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYBOOLEANARRAY
#include 'NAVTomlQueryBooleanArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYLONGARRAY
#include 'NAVTomlQueryLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDLONGARRAY
#include 'NAVTomlQuerySignedLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLESCAPESEQUENCES
#include 'NAVTomlEscapeSequences.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLDEEPNESTING
#include 'NAVTomlDeepNesting.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLLARGEARRAYS
#include 'NAVTomlLargeArrays.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLLIMITS
#include 'NAVTomlLimits.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLNAVIGATIONEDGECASES
#include 'NAVTomlNavigationEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLQUERYEDGECASES
#include 'NAVTomlQueryEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLPARSERUNESCAPESTRING
#include 'NAVTomlParserUnescapeString.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLTREEINFO
#include 'NAVTomlTreeInfo.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLVALIDATION
#include 'NAVTomlValidation.axi'
#END_IF

#IF_DEFINED TESTING_NAVTOMLVALUEGETTERS
#include 'NAVTomlValueGetters.axi'
#END_IF


define_function RunTomlTests() {
    #IF_DEFINED TESTING_NAVTOMLLEXERTOKENIZE
    TestNAVTomlLexerTokenize()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLLEXEREDGECASES
    TestNAVTomlLexerEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLPARSE
    TestNAVTomlParse()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERY
    TestNAVTomlQuery()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYSTRING
    TestNAVTomlQueryString()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYINTEGER
    TestNAVTomlQueryInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDINTEGER
    TestNAVTomlQuerySignedInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYFLOAT
    TestNAVTomlQueryFloat()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYBOOLEAN
    TestNAVTomlQueryBoolean()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYLONG
    TestNAVTomlQueryLong()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDLONG
    TestNAVTomlQuerySignedLong()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLTYPECHECKING
    TestNAVTomlTypeChecking()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLGETPARENTNODE
    TestNAVTomlGetParentNode()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYSTRINGARRAY
    TestNAVTomlQueryStringArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYINTEGERARRAY
    TestNAVTomlQueryIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDINTEGERARRAY
    TestNAVTomlQuerySignedIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYFLOATARRAY
    TestNAVTomlQueryFloatArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYBOOLEANARRAY
    TestNAVTomlQueryBooleanArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYLONGARRAY
    TestNAVTomlQueryLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYSIGNEDLONGARRAY
    TestNAVTomlQuerySignedLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLESCAPESEQUENCES
    TestNAVTomlEscapeSequences()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLDEEPNESTING
    TestNAVTomlDeepNesting()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLLARGEARRAYS
    TestNAVTomlLargeArrays()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLLIMITS
    TestNAVTomlLimits()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLNAVIGATIONEDGECASES
    TestNAVTomlNavigationEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLQUERYEDGECASES
    TestNAVTomlQueryEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLPARSERUNESCAPESTRING
    TestNAVTomlParserUnescapeString()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLTREEINFO
    TestNAVTomlTreeInfo()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLVALIDATION
    TestNAVTomlValidation()
    #END_IF

    #IF_DEFINED TESTING_NAVTOMLVALUEGETTERS
    TestNAVTomlValueGetters()
    #END_IF
}
