build:
  nlrc:
    includePath:
      - ./ArrayUtils
      - ./Assert
      - ./BinaryUtils
      - ./Console
      - ./Core
      - ./Cryptography
      - ./DateTimeUtils
      - ./ErrorLogUtils
      - ./Encoding
      - ./Enova
      - ./FileUtils
      - ./HashTable
      - ./HttpUtils
      - ./IniUtils
      - ./Int64
      - ./InterModuleApi
      - ./Jsmn
      - ./Json
      - ./Lexer
      - ./LogicEngine
      - ./Math
      - ./McpBase
      - ./NtpClient
      - ./PathUtils
      - ./Queue
      - ./Regex
      - ./RmsBase
      - ./SnapiHelpers
      - ./SocketUtils
      - ./Stack
      - ./Stopwatch
      - ./StringUtils
      - ./Testing
      - ./TimelineUtils
      - ./Tui
      - ./UIUtils
      - ./Url
      - ./__tests__/include/aes128
      - ./__tests__/include/hash-table
      - ./__tests__/include/path-utils
      - ./__tests__/include/pbkdf2
      - ./__tests__/include/regex
      - ./__tests__/include/string-utils
      - ./__tests__/include/aes128
      - ./__tests__/include/pbkdf2
      - ./__tests__/include/ini-utils
      - ./__tests__/include/int64
      - ./__tests__/include/assert
      - ./__tests__/include/sha1
      - ./__tests__/include/sha512
      - ./__tests__/include/sha256
      - ./__tests__/include/md5
      - ./__tests__/include/base64
      - ./__tests__/include/base32
      - ./__tests__/include/http
      - ./__tests__/include/url
      - ./__tests__/include/jsmn
      - ./__tests__/include/queue
