build:
  nlrc:
    includePath:
      - ./ArrayUtils
      - ./Assert
      - ./BinaryUtils
      - ./Console
      - ./Core
      - ./Cryptography
      - ./DateTimeUtils
      - ./ErrorLogUtils
      - ./Encoding
      - ./Enova
      - ./FileUtils
      - ./HashTable
      - ./HttpUtils
      - ./IniParser
      - ./Int64
      - ./Jsmn
      - ./Json
      - ./Lexer
      - ./LogicEngine
      - ./Math
      - ./McpBase
      - ./NtpClient
      - ./PathUtils
      - ./Queue
      - ./Regex
      - ./RmsBase
      - ./SnapiHelpers
      - ./SocketUtils
      - ./Stack
      - ./Stopwatch
      - ./StringUtils
      - ./Testing
      - ./TimelineUtils
      - ./Tui
      - ./UIUtils
      - ./Url
      - ./__tests__/include/path-utils
      - ./__tests__/include/regex
      - ./__tests__/include/string-utils
      - ./__tests__/include/aes128
      - ./__tests__/include/pbkdf2
      - ./__tests__/include/assert
      - ./include
    modulePath:
      - ./module
