build:
  nlrc:
    includePath:
      - ./ArrayUtils
      - ./Assert
      - ./BinaryUtils
      - ./Core
      - ./Cryptography
      - ./CsvUtils
      - ./DateTimeUtils
      - ./ErrorLogUtils
      - ./Encoding
      - ./Enova
      - ./Figlet
      - ./FileUtils
      - ./HashTable
      - ./HttpUtils
      - ./IniUtils
      - ./Int64
      - ./InterModuleApi
      - ./Jsmn
      - ./Json
      - ./Lexer
      - ./List
      - ./LogicEngine
      - ./Math
      - ./McpBase
      - ./NetUtils
      - ./NtpUtils
      - ./PathUtils
      - ./Queue
      - ./Regex
      - ./RmsBase
      - ./SnapiHelpers
      - ./SocketUtils
      - ./Stack
      - ./Stopwatch
      - ./StringUtils
      - ./Testing
      - ./TimelineUtils
      - ./Toml
      - ./Tui
      - ./UIUtils
      - ./Url
      - ./WebSocket
      - ./Xml
      - ./Yaml
      - ./__tests__/include/aes128
      - ./__tests__/include/hash-table
      - ./__tests__/include/path-utils
      - ./__tests__/include/pbkdf2
      - ./__tests__/include/regex
      - ./__tests__/include/string-utils
      - ./__tests__/include/aes128
      - ./__tests__/include/pbkdf2
      - ./__tests__/include/ini-utils
      - ./__tests__/include/int64
      - ./__tests__/include/assert
      - ./__tests__/include/sha1
      - ./__tests__/include/sha512
      - ./__tests__/include/sha256
      - ./__tests__/include/md5
      - ./__tests__/include/base64
      - ./__tests__/include/base32
      - ./__tests__/include/http-utils
      - ./__tests__/include/url
      - ./__tests__/include/jsmn
      - ./__tests__/include/queue
      - ./__tests__/include/array-utils
      - ./__tests__/include/stack
      - ./__tests__/include/encoding
      - ./__tests__/include/tui
      - ./__tests__/include/csv-utils
      - ./__tests__/include/stack-overflow
      - ./__tests__/include/date-time-utils
      - ./__tests__/include/snapi-helpers
      - ./__tests__/include/file-utils
      - ./__tests__/include/binary-utils
      - ./__tests__/include/figlet
      - ./__tests__/include/net-utils
      - ./__tests__/include/list
      - ./__tests__/include/websocket
      - ./__tests__/include/json
      - ./__tests__/include/cloudlog
      - ./__tests__/include/core
      - ./__tests__/include/socket-utils
      - ./__tests__/include/xml
      - ./__tests__/include/yaml
      - ./__tests__/include/toml
      - ./__tests__/include/hmac
      - ./__tests__/include/base64url
