#DEFINE TESTING_NAVDATETIMEISLEAPYEAR
#DEFINE TESTING_NAVDATETIMEGETYEARDAY
#DEFINE TESTING_NAVDATETIMEEPOCHCONVERSION
#DEFINE TESTING_NAVDATETIMEISDST
#DEFINE TESTING_NAVDATETIMEGETTIMESPEC
#DEFINE TESTING_NAVDATETIMEGETGMTOFFSET
#DEFINE TESTING_NAVDATETIMEGETTIMESTAMPFORMAT
#DEFINE TESTING_NAVDATETIMEGETNEXTDATE
#DEFINE TESTING_NAVDATETIMEGETDAYSINMONTH
#DEFINE TESTING_NAVDATETIMEGETDIFFERENCE
#DEFINE TESTING_NAVDATETIMETIMESPECPAST
#DEFINE TESTING_NAVDATETIMEGETLASTSUNDAYINMONTH

#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.DateTimeUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVDATETIMEISLEAPYEAR
#include 'NAVDateTimeIsLeapYear.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETYEARDAY
#include 'NAVDateTimeGetYearDay.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEEPOCHCONVERSION
#include 'NAVDateTimeEpochConversion.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEISDST
#include 'NAVDateTimeIsDst.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETTIMESPEC
#include 'NAVDateTimeGetTimespec.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETGMTOFFSET
#include 'NAVDateTimeGetGmtOffset.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETTIMESTAMPFORMAT
#include 'NAVDateTimeGetTimestampFormat.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETNEXTDATE
#include 'NAVDAteTimeGetNextDate.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETDAYSINMONTH
#include 'NAVDateTimeGetDaysInMonth.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETDIFFERENCE
#include 'NAVDateTimeGetDifference.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMETIMESPECPAST
#include 'NAVDateTimeTimespecPast.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMEGETLASTSUNDAYINMONTH
#include 'NAVDateTimeGetLastSundayInMonth.axi'
#END_IF

#IF_DEFINED TESTING_NAVDATETIMESETCLOCKFROMTIMESPEC
#include 'NAVDateTimeSetClockFromTimespec.axi'
#END_IF

define_function RunDateTimeUtilsTests() {
    #IF_DEFINED TESTING_NAVDATETIMEISLEAPYEAR
    TestNAVDateTimeIsLeapYear()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETYEARDAY
    TestNAVDateTimeGetYearDay()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEEPOCHCONVERSION
    TestNAVDateTimeEpochToTimespec()
    TestNAVDateTimeGetEpoch()
    TestNAVDateTimeEpochRoundTrip()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEISDST
    TestNAVDateTimeIsDst()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETTIMESPEC
    TestNAVDateTimeGetTimespec()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETGMTOFFSET
    TestNAVDateTimeGetGmtOffset()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETTIMESTAMPFORMAT
    TestNAVDateTimeGetTimestampFormat()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETNEXTDATE
    TestNAVDateTimeGetNextDate()
    TestNAVDateTimeGetNextDateInvalidInput()
    TestNAVDateTimeGetNextDateEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETDAYSINMONTH
    TestNAVDateTimeGetDaysInMonth()
    TestNAVDateTimeGetDaysInMonthInvalidInput()
    TestNAVDateTimeGetDaysInMonthLeapYearEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETDIFFERENCE
    TestNAVDateTimeGetDifference()
    TestNAVDateTimeGetDifferenceEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMETIMESPECPAST
    TestNAVDateTimeTimespecPast()
    TestNAVDateTimeTimespecPastEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVDATETIMEGETLASTSUNDAYINMONTH
    TestNAVDateTimeGetLastSundayInMonth()
    TestNAVDateTimeGetLastSundayInMonthEdgeCases()
    TestNAVDateTimeGetLastSundayInMonthDSTValidation()
    #END_IF
}
