#DEFINE TESTING_NAVSOCKETGETEXPONENTIALBACKOFF
#DEFINE TESTING_NAVSOCKETGETCONNECTIONINTERVAL
#DEFINE TESTING_NAVSOCKETCONNECTIONINIT
#DEFINE TESTING_NAVSOCKETCONNECTIONSETADDRESS
#DEFINE TESTING_NAVSOCKETCONNECTIONSETPORT
#DEFINE TESTING_NAVSOCKETCONNECTIONSETCREDENTIAL
#DEFINE TESTING_NAVSOCKETCONNECTIONSETSSHPRIVATEKEY
#DEFINE TESTING_NAVSOCKETCONNECTIONSETTLSMODE
#DEFINE TESTING_NAVSOCKETCONNECTIONISCONFIGURED
#DEFINE TESTING_NAVISSOCKETDEVICE
#DEFINE TESTING_NAVSOCKETCONNECTIONGETSTATUS
#DEFINE TESTING_NAVSOCKETCONNECTIONGETCONNECTIONTYPESTRING
#DEFINE TESTING_NAVSOCKETCONNECTIONISRETRYING
#DEFINE TESTING_NAVSOCKETCONNECTIONISCONNECTED
#DEFINE TESTING_NAVSOCKETCONNECTIONGETINFO
#DEFINE TESTING_NAVSOCKETCONNECTIONISINITIALIZED
#include 'NAVFoundation.SocketUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVSOCKETGETEXPONENTIALBACKOFF
#include 'NAVSocketGetExponentialBackoff.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETGETCONNECTIONINTERVAL
#include 'NAVSocketGetConnectionInterval.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONINIT
#include 'NAVSocketConnectionInit.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETADDRESS
#include 'NAVSocketConnectionSetAddress.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETPORT
#include 'NAVSocketConnectionSetPort.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETCREDENTIAL
#include 'NAVSocketConnectionSetCredential.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETSSHPRIVATEKEY
#include 'NAVSocketConnectionSetSshPrivateKey.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETTLSMODE
#include 'NAVSocketConnectionSetTlsMode.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONISCONFIGURED
#include 'NAVSocketConnectionIsConfigured.axi'
#END_IF

#IF_DEFINED TESTING_NAVISSOCKETDEVICE
#include 'NAVIsSocketDevice.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONGETSTATUS
#include 'NAVSocketConnectionGetStatus.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONGETCONNECTIONTYPESTRING
#include 'NAVSocketConnectionGetConnectionTypeString.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONISRETRYING
#include 'NAVSocketConnectionIsRetrying.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONISCONNECTED
#include 'NAVSocketConnectionIsConnected.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONGETINFO
#include 'NAVSocketConnectionGetInfo.axi'
#END_IF

#IF_DEFINED TESTING_NAVSOCKETCONNECTIONISINITIALIZED
#include 'NAVSocketConnectionIsInitialized.axi'
#END_IF


define_function RunSocketUtilsTests() {
    #IF_DEFINED TESTING_NAVSOCKETGETEXPONENTIALBACKOFF
    TestNAVSocketGetExponentialBackoff()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETGETCONNECTIONINTERVAL
    TestNAVSocketGetConnectionInterval()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONINIT
    TestNAVSocketConnectionInit()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETADDRESS
    TestNAVSocketConnectionSetAddress()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETPORT
    TestNAVSocketConnectionSetPort()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETCREDENTIAL
    TestNAVSocketConnectionSetCredential()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETSSHPRIVATEKEY
    TestNAVSocketConnectionSetSshPrivateKey()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONSETTLSMODE
    TestNAVSocketConnectionSetTlsMode()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONISCONFIGURED
    TestNAVSocketConnectionIsConfigured()
    #END_IF

    #IF_DEFINED TESTING_NAVISSOCKETDEVICE
    TestNAVIsSocketDevice()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONGETSTATUS
    TestNAVSocketConnectionGetStatus()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONGETCONNECTIONTYPESTRING
    TestNAVSocketConnectionGetConnectionTypeString()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONISRETRYING
    TestNAVSocketConnectionIsRetrying()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONISCONNECTED
    TestNAVSocketConnectionIsConnected()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONGETINFO
    TestNAVSocketConnectionGetInfo()
    #END_IF

    #IF_DEFINED TESTING_NAVSOCKETCONNECTIONISINITIALIZED
    TestNAVSocketConnectionIsInitialized()
    #END_IF
}
