#DEFINE TESTING_NAVXMLLEXERTOKENIZE
#DEFINE TESTING_NAVXMLPARSE
#DEFINE TESTING_NAVXMLQUERY
#DEFINE TESTING_NAVXMLQUERYSTRING
#DEFINE TESTING_NAVXMLQUERYBOOLEAN
#DEFINE TESTING_NAVXMLQUERYFLOAT
#DEFINE TESTING_NAVXMLQUERYINTEGER
#DEFINE TESTING_NAVXMLQUERYSIGNEDINTEGER
#DEFINE TESTING_NAVXMLQUERYLONG
#DEFINE TESTING_NAVXMLQUERYSIGNEDLONG
#DEFINE TESTING_NAVXMLQUERYSTRINGARRAY
#DEFINE TESTING_NAVXMLQUERYBOOLEANARRAY
#DEFINE TESTING_NAVXMLQUERYFLOATARRAY
#DEFINE TESTING_NAVXMLQUERYINTEGERARRAY
#DEFINE TESTING_NAVXMLQUERYSIGNEDINTEGERARRAY
#DEFINE TESTING_NAVXMLQUERYLONGARRAY
#DEFINE TESTING_NAVXMLQUERYSIGNEDLONGARRAY
#DEFINE TESTING_NAVXMLDEEPNESTING
#DEFINE TESTING_NAVXMLESCAPESTRING
#DEFINE TESTING_NAVXMLGETPARENTNODE
#DEFINE TESTING_NAVXMLLARGEARRAYS
#DEFINE TESTING_NAVXMLLIMITS
#DEFINE TESTING_NAVXMLNAVIGATIONEDGECASES
#DEFINE TESTING_NAVXMLNODEHELPERS
#DEFINE TESTING_NAVXMLPARSERUNESCAPESTRING
#DEFINE TESTING_NAVXMLTREEINFO
#DEFINE TESTING_NAVXMLTYPECHECKING
#DEFINE TESTING_NAVXMLVALIDATION
#DEFINE TESTING_NAVXMLVALUEGETTERS
#DEFINE TESTING_NAVXMLNAMESPACE
#DEFINE TESTING_NAVXMLPROCESSINGINSTRUCTIONS
#DEFINE TESTING_NAVXMLARRAYCONVERTERS
// #DEFINE XML_LEXER_DEBUG
// #DEFINE XML_PARSER_DEBUG
// #DEFINE XML_QUERY_DEBUG
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Xml.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVXMLLEXERTOKENIZE
#include 'NAVXmlLexerTokenize.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLPARSE
#include 'NAVXmlParse.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERY
#include 'NAVXmlQuery.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYSTRING
#include 'NAVXmlQueryString.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYBOOLEAN
#include 'NAVXmlQueryBoolean.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYFLOAT
#include 'NAVXmlQueryFloat.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYINTEGER
#include 'NAVXmlQueryInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYSIGNEDINTEGER
#include 'NAVXmlQuerySignedInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYLONG
#include 'NAVXmlQueryLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYSIGNEDLONG
#include 'NAVXmlQuerySignedLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYSTRINGARRAY
#include 'NAVXmlQueryStringArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYBOOLEANARRAY
#include 'NAVXmlQueryBooleanArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYFLOATARRAY
#include 'NAVXmlQueryFloatArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYINTEGERARRAY
#include 'NAVXmlQueryIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYSIGNEDINTEGERARRAY
#include 'NAVXmlQuerySignedIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYLONGARRAY
#include 'NAVXmlQueryLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLQUERYSIGNEDLONGARRAY
#include 'NAVXmlQuerySignedLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLDEEPNESTING
#include 'NAVXmlDeepNesting.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLESCAPESTRING
#include 'NAVXmlEscapeString.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLGETPARENTNODE
#include 'NAVXmlGetParentNode.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLLARGEARRAYS
#include 'NAVXmlLargeArrays.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLLIMITS
#include 'NAVXmlLimits.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLNAVIGATIONEDGECASES
#include 'NAVXmlNavigationEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLNODEHELPERS
#include 'NAVXmlNodeHelpers.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLPARSERUNESCAPESTRING
#include 'NAVXmlParserUnescapeString.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLTREEINFO
#include 'NAVXmlTreeInfo.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLTYPECHECKING
#include 'NAVXmlTypeChecking.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLVALIDATION
#include 'NAVXmlValidation.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLVALUEGETTERS
#include 'NAVXmlValueGetters.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLNAMESPACE
#include 'NAVXmlNamespace.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLPROCESSINGINSTRUCTIONS
#include 'NAVXmlProcessingInstructions.axi'
#END_IF

#IF_DEFINED TESTING_NAVXMLARRAYCONVERTERS
#include 'NAVXmlArrayConverters.axi'
#END_IF


define_function RunXmlTests() {
    #IF_DEFINED TESTING_NAVXMLLEXERTOKENIZE
    TestNAVXmlLexerTokenize()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLPARSE
    TestNAVXmlParse()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERY
    TestNAVXmlQuery()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYSTRING
    TestNAVXmlQueryString()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYBOOLEAN
    TestNAVXmlQueryBoolean()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYFLOAT
    TestNAVXmlQueryFloat()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYINTEGER
    TestNAVXmlQueryInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYSIGNEDINTEGER
    TestNAVXmlQuerySignedInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYLONG
    TestNAVXmlQueryLong()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYSIGNEDLONG
    TestNAVXmlQuerySignedLong()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYSTRINGARRAY
    TestNAVXmlQueryStringArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYBOOLEANARRAY
    TestNAVXmlQueryBooleanArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYFLOATARRAY
    TestNAVXmlQueryFloatArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYINTEGERARRAY
    TestNAVXmlQueryIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYSIGNEDINTEGERARRAY
    TestNAVXmlQuerySignedIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYLONGARRAY
    TestNAVXmlQueryLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLQUERYSIGNEDLONGARRAY
    TestNAVXmlQuerySignedLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLDEEPNESTING
    TestNAVXmlDeepNesting()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLESCAPESTRING
    TestNAVXmlEscapeString()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLGETPARENTNODE
    TestNAVXmlGetParentNode()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLLARGEARRAYS
    TestNAVXmlLargeArrays()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLLIMITS
    TestNAVXmlLimits()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLNAVIGATIONEDGECASES
    TestNAVXmlNavigationEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLNODEHELPERS
    TestNAVXmlNodeHelpers()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLPARSERUNESCAPESTRING
    TestNAVXmlParserUnescapeString()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLTREEINFO
    TestNAVXmlTreeInfo()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLTYPECHECKING
    TestNAVXmlTypeChecking()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLVALIDATION
    TestNAVXmlValidation()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLVALUEGETTERS
    TestNAVXmlValueGetters()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLNAMESPACE
    TestNAVXmlNamespace()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLPROCESSINGINSTRUCTIONS
    TestNAVXmlProcessingInstructions()
    #END_IF

    #IF_DEFINED TESTING_NAVXMLARRAYCONVERTERS
    TestNAVXmlArrayConverters()
    #END_IF
}
