#DEFINE TESTING_NAVYAMLLEXERTOKENIZE
#DEFINE TESTING_NAVYAMLPARSE
#DEFINE TESTING_NAVYAMLTYPECHECKING
#DEFINE TESTING_NAVYAMLVALUEGETTERS
#DEFINE TESTING_NAVYAMLMAPPINGSEQUENCEHELPERS
#DEFINE TESTING_NAVYAMLQUERY
#DEFINE TESTING_NAVYAMLQUERYSTRING
#DEFINE TESTING_NAVYAMLQUERYBOOLEAN
#DEFINE TESTING_NAVYAMLQUERYFLOAT
#DEFINE TESTING_NAVYAMLQUERYINTEGER
#DEFINE TESTING_NAVYAMLQUERYSIGNEDINTEGER
#DEFINE TESTING_NAVYAMLQUERYLONG
#DEFINE TESTING_NAVYAMLQUERYSIGNEDLONG
#DEFINE TESTING_NAVYAMLQUERYSTRINGARRAY
#DEFINE TESTING_NAVYAMLQUERYINTEGERARRAY
#DEFINE TESTING_NAVYAMLQUERYSIGNEDINTEGERARRAY
#DEFINE TESTING_NAVYAMLQUERYFLOATARRAY
#DEFINE TESTING_NAVYAMLQUERYBOOLEANARRAY
#DEFINE TESTING_NAVYAMLQUERYLONGARRAY
#DEFINE TESTING_NAVYAMLQUERYSIGNEDLONGARRAY
#DEFINE TESTING_NAVYAMLGETPARENTNODE
#DEFINE TESTING_NAVYAMLQUERYEDGECASES
#DEFINE TESTING_NAVYAMLQUERYNULL
#DEFINE TESTING_NAVYAMLDEEPNESTING
#DEFINE TESTING_NAVYAMLLARGESEQUENCES
#DEFINE TESTING_NAVYAMLLIMITS
#DEFINE TESTING_NAVYAMLNAVIGATIONEDGECASES
#DEFINE TESTING_NAVYAMLBLOCKSCALARS
#DEFINE TESTING_NAVYAMLBLOCKSCALARCHOMPING
#DEFINE TESTING_NAVYAMLEXPLICITINDENTATION
#DEFINE TESTING_NAVYAMLESCAPESEQUENCES
#DEFINE TESTING_NAVYAMLMERGEKEYS
#DEFINE TESTING_NAVYAMLDIRECTIVES
#DEFINE TESTING_NAVYAMLANCHORSALIASES
#DEFINE TESTING_NAVYAMLFLOWSTYLE
#DEFINE TESTING_NAVYAMLTREEINFO
#DEFINE TESTING_NAVYAMLVALIDATION
#DEFINE TESTING_NAVYAMLTAGS
#DEFINE TESTING_NAVYAMLEXPLICITKEYS
// #DEFINE YAML_LEXER_DEBUG
// #DEFINE YAML_PARSER_DEBUG
// #DEFINE YAML_QUERY_DEBUG
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Yaml.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVYAMLLEXERTOKENIZE
#include 'NAVYamlLexerTokenize.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLPARSE
#include 'NAVYamlParse.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLTYPECHECKING
#include 'NAVYamlTypeChecking.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLVALUEGETTERS
#include 'NAVYamlValueGetters.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLMAPPINGSEQUENCEHELPERS
#include 'NAVYamlMappingSequenceHelpers.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERY
#include 'NAVYamlQuery.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYSTRING
#include 'NAVYamlQueryString.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYBOOLEAN
#include 'NAVYamlQueryBoolean.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYFLOAT
#include 'NAVYamlQueryFloat.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYINTEGER
#include 'NAVYamlQueryInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDINTEGER
#include 'NAVYamlQuerySignedInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYLONG
#include 'NAVYamlQueryLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDLONG
#include 'NAVYamlQuerySignedLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYDOUBLE
#include 'NAVYamlQueryDouble.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYSTRINGARRAY
#include 'NAVYamlQueryStringArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYINTEGERARRAY
#include 'NAVYamlQueryIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYFLOATARRAY
#include 'NAVYamlQueryFloatArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYBOOLEANARRAY
#include 'NAVYamlQueryBooleanArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDINTEGERARRAY
#include 'NAVYamlQuerySignedIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYLONGARRAY
#include 'NAVYamlQueryLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDLONGARRAY
#include 'NAVYamlQuerySignedLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYDOUBLEARRAY
#include 'NAVYamlQueryDoubleArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLGETPARENTNODE
#include 'NAVYamlGetParentNode.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYEDGECASES
#include 'NAVYamlQueryEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLQUERYNULL
#include 'NAVYamlQueryNull.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLDEEPNESTING
#include 'NAVYamlDeepNesting.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLLARGESEQUENCES
#include 'NAVYamlLargeSequences.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLLIMITS
#include 'NAVYamlLimits.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLNAVIGATIONEDGECASES
#include 'NAVYamlNavigationEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLBLOCKSCALARS
#include 'NAVYamlBlockScalars.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLBLOCKSCALARCHOMPING
#include 'NAVYamlBlockScalarChomping.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLEXPLICITINDENTATION
#include 'NAVYamlExplicitIndentation.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLESCAPESEQUENCES
#include 'NAVYamlEscapeSequences.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLMERGEKEYS
#include 'NAVYamlMergeKeys.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLDIRECTIVES
#include 'NAVYamlDirectives.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLANCHORSALIASES
#include 'NAVYamlAnchorsAliases.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLFLOWSTYLE
#include 'NAVYamlFlowStyle.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLTREEINFO
#include 'NAVYamlTreeInfo.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLVALIDATION
#include 'NAVYamlValidation.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLTAGS
#include 'NAVYamlTags.axi'
#END_IF

#IF_DEFINED TESTING_NAVYAMLEXPLICITKEYS
#include 'NAVYamlExplicitKeys.axi'
#END_IF


define_function RunYamlTests() {
    #IF_DEFINED TESTING_NAVYAMLLEXERTOKENIZE
    TestNAVYamlLexerTokenize()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLPARSE
    TestNAVYamlParse()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLTYPECHECKING
    TestNAVYamlTypeChecking()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLVALUEGETTERS
    TestNAVYamlValueGetters()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLMAPPINGSEQUENCEHELPERS
    TestNAVYamlMappingSequenceHelpers()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERY
    TestNAVYamlQuery()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYSTRING
    TestNAVYamlQueryString()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYBOOLEAN
    TestNAVYamlQueryBoolean()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYFLOAT
    TestNAVYamlQueryFloat()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYINTEGER
    TestNAVYamlQueryInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDINTEGER
    TestNAVYamlQuerySignedInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYLONG
    TestNAVYamlQueryLong()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDLONG
    TestNAVYamlQuerySignedLong()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYDOUBLE
    TestNAVYamlQueryDouble()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYSTRINGARRAY
    TestNAVYamlQueryStringArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYINTEGERARRAY
    TestNAVYamlQueryIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYFLOATARRAY
    TestNAVYamlQueryFloatArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYBOOLEANARRAY
    TestNAVYamlQueryBooleanArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDINTEGERARRAY
    TestNAVYamlQuerySignedIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYLONGARRAY
    TestNAVYamlQueryLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYSIGNEDLONGARRAY
    TestNAVYamlQuerySignedLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYDOUBLEARRAY
    TestNAVYamlQueryDoubleArray()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLGETPARENTNODE
    TestNAVYamlGetParentNode()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYEDGECASES
    TestNAVYamlQueryEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLQUERYNULL
    TestNAVYamlQueryNull()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLDEEPNESTING
    TestNAVYamlDeepNesting()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLLARGESEQUENCES
    TestNAVYamlLargeSequences()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLLIMITS
    TestNAVYamlLimits()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLNAVIGATIONEDGECASES
    TestNAVYamlNavigationEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLBLOCKSCALARS
    TestNAVYamlBlockScalars()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLBLOCKSCALARCHOMPING
    TestNAVYamlBlockScalarChomping()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLEXPLICITINDENTATION
    TestNAVYamlExplicitIndentation()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLESCAPESEQUENCES
    TestNAVYamlEscapeSequences()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLMERGEKEYS
    TestNAVYamlMergeKeys()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLDIRECTIVES
    TestNAVYamlDirectives()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLANCHORSALIASES
    TestNAVYamlAnchorsAliases()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLFLOWSTYLE
    TestNAVYamlFlowStyle()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLTREEINFO
    TestNAVYamlTreeInfo()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLVALIDATION
    TestNAVYamlValidation()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLTAGS
    TestNAVYamlTags()
    #END_IF

    #IF_DEFINED TESTING_NAVYAMLEXPLICITKEYS
    TestNAVYamlExplicitKeys()
    #END_IF
}
