#DEFINE TESTING_NAVJSONLEXERTOKENIZE
#DEFINE TESTING_NAVJSONPARSERUNESCAPESTRING
#DEFINE TESTING_NAVJSONESCAPESTRING
#DEFINE TESTING_NAVJSONPARSE
#DEFINE TESTING_NAVJSONTYPECHECKING
#DEFINE TESTING_NAVJSONVALUEGETTERS
#DEFINE TESTING_NAVJSONOBJECTARRAYHELPERS
#DEFINE TESTING_NAVJSONVALIDATION
#DEFINE TESTING_NAVJSONTREEINFO
#DEFINE TESTING_NAVJSONQUERY
#DEFINE TESTING_NAVJSONQUERYSTRING
#DEFINE TESTING_NAVJSONQUERYBOOLEAN
#DEFINE TESTING_NAVJSONQUERYFLOAT
#DEFINE TESTING_NAVJSONQUERYINTEGER
#DEFINE TESTING_NAVJSONQUERYSIGNEDINTEGER
#DEFINE TESTING_NAVJSONQUERYLONG
#DEFINE TESTING_NAVJSONQUERYSIGNEDLONG
#DEFINE TESTING_NAVJSONQUERYBOOLEANARRAY
#DEFINE TESTING_NAVJSONQUERYFLOATARRAY
#DEFINE TESTING_NAVJSONQUERYINTEGERARRAY
#DEFINE TESTING_NAVJSONQUERYSIGNEDINTEGERARRAY
#DEFINE TESTING_NAVJSONQUERYLONGARRAY
#DEFINE TESTING_NAVJSONQUERYSIGNEDLONGARRAY
#DEFINE TESTING_NAVJSONGETPARENTNODE
#DEFINE TESTING_NAVJSONQUERYEDGECASES
#DEFINE TESTING_NAVJSONMIXEDTYPEARRAYS
#DEFINE TESTING_NAVJSONQUERYNULL
#DEFINE TESTING_NAVJSONDEEPNESTING
#DEFINE TESTING_NAVJSONLARGEARRAYS
#DEFINE TESTING_NAVJSONLIMITS
#DEFINE TESTING_NAVJSONNAVIGATIONEDGECASES
// #DEFINE JSON_LEXER_DEBUG
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Json.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVJSONLEXERTOKENIZE
#include 'NAVJsonLexerTokenize.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONPARSERUNESCAPESTRING
#include 'NAVJsonParserUnescapeString.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONESCAPESTRING
#include 'NAVJsonEscapeString.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONPARSE
#include 'NAVJsonParse.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONTYPECHECKING
#include 'NAVJsonTypeChecking.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONVALUEGETTERS
#include 'NAVJsonValueGetters.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONOBJECTARRAYHELPERS
#include 'NAVJsonObjectArrayHelpers.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONVALIDATION
#include 'NAVJsonValidation.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONTREEINFO
#include 'NAVJsonTreeInfo.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERY
#include 'NAVJsonQuery.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYSTRING
#include 'NAVJsonQueryString.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYBOOLEAN
#include 'NAVJsonQueryBoolean.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYFLOAT
#include 'NAVJsonQueryFloat.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYINTEGER
#include 'NAVJsonQueryInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYSIGNEDINTEGER
#include 'NAVJsonQuerySignedInteger.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYLONG
#include 'NAVJsonQueryLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYSIGNEDLONG
#include 'NAVJsonQuerySignedLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYBOOLEANARRAY
#include 'NAVJsonQueryBooleanArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYFLOATARRAY
#include 'NAVJsonQueryFloatArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYINTEGERARRAY
#include 'NAVJsonQueryIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYSIGNEDINTEGERARRAY
#include 'NAVJsonQuerySignedIntegerArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYLONGARRAY
#include 'NAVJsonQueryLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYSIGNEDLONGARRAY
#include 'NAVJsonQuerySignedLongArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONGETPARENTNODE
#include 'NAVJsonGetParentNode.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYEDGECASES
#include 'NAVJsonQueryEdgeCases.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONMIXEDTYPEARRAYS
#include 'NAVJsonMixedTypeArrays.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONQUERYNULL
#include 'NAVJsonQueryNull.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONDEEPNESTING
#include 'NAVJsonDeepNesting.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONLARGEARRAYS
#include 'NAVJsonLargeArrays.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONLIMITS
#include 'NAVJsonLimits.axi'
#END_IF

#IF_DEFINED TESTING_NAVJSONNAVIGATIONEDGECASES
#include 'NAVJsonNavigationEdgeCases.axi'
#END_IF

define_function RunJsonTests() {
    #IF_DEFINED TESTING_NAVJSONLEXERTOKENIZE
    TestNAVJsonLexerTokenize()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONPARSERUNESCAPESTRING
    TestNAVJsonParserUnescapeString()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONESCAPESTRING
    TestNAVJsonEscapeString()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONPARSE
    TestNAVJsonParse()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONTYPECHECKING
    TestNAVJsonTypeChecking()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONVALUEGETTERS
    TestNAVJsonValueGetters()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONOBJECTARRAYHELPERS
    TestNAVJsonObjectArrayHelpers()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONVALIDATION
    TestNAVJsonValidation()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONTREEINFO
    TestNAVJsonTreeInfo()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERY
    TestNAVJsonQuery()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYSTRING
    TestNAVJsonQueryString()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYBOOLEAN
    TestNAVJsonQueryBoolean()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYFLOAT
    TestNAVJsonQueryFloat()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYINTEGER
    TestNAVJsonQueryInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYSIGNEDINTEGER
    TestNAVJsonQuerySignedInteger()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYLONG
    TestNAVJsonQueryLong()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYSIGNEDLONG
    TestNAVJsonQuerySignedLong()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYBOOLEANARRAY
    TestNAVJsonQueryBooleanArray()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYFLOATARRAY
    TestNAVJsonQueryFloatArray()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYINTEGERARRAY
    TestNAVJsonQueryIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYSIGNEDINTEGERARRAY
    TestNAVJsonQuerySignedIntegerArray()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYLONGARRAY
    TestNAVJsonQueryLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYSIGNEDLONGARRAY
    TestNAVJsonQuerySignedLongArray()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONGETPARENTNODE
    TestNAVJsonGetParentNode()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYEDGECASES
    TestNAVJsonQueryEdgeCases()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONMIXEDTYPEARRAYS
    TestNAVJsonMixedTypeArrays()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONQUERYNULL
    TestNAVJsonQueryNull()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONDEEPNESTING
    TestNAVJsonDeepNesting()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONLARGEARRAYS
    TestNAVJsonLargeArrays()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONLIMITS
    TestNAVJsonLimits()
    #END_IF

    #IF_DEFINED TESTING_NAVJSONNAVIGATIONEDGECASES
    TestNAVJsonNavigationEdgeCases()
    #END_IF
}
