#DEFINE TESTING_NAVSNAPILEXER
#DEFINE TESTING_NAVSNAPIPARSER
#DEFINE TESTING_NAVSNAPIPARSEMESSAGE
#DEFINE TESTING_DUETPARSECMD
// #DEFINE SNAPI_LEXER_DEBUG
// #DEFINE SNAPI_PARSER_DEBUG
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVSNAPILEXER
#include 'NAVSnapiLexer.axi'
#END_IF

#IF_DEFINED TESTING_NAVSNAPIPARSER
#include 'NAVSnapiParser.axi'
#END_IF

#IF_DEFINED TESTING_NAVSNAPIPARSEMESSAGE
#include 'NAVSnapiParseMessage.axi'
#END_IF

#IF_DEFINED TESTING_DUETPARSECMD
#include 'DuetParseCmd.axi'
#END_IF

define_function RunSnapiHelpersTests() {
    #IF_DEFINED TESTING_NAVSNAPILEXER
    TestNAVSnapiLexerBasic()
    #END_IF

    #IF_DEFINED TESTING_NAVSNAPIPARSER
    TestNAVSnapiParserBasic()
    #END_IF

    #IF_DEFINED TESTING_NAVSNAPIPARSEMESSAGE
    TestNAVSnapiParseMessage()
    #END_IF

    #IF_DEFINED TESTING_DUETPARSECMD
    TestDuetParseCmd()
    #END_IF
}

