#DEFINE TESTING_NAVGETCOLOR
#DEFINE TESTING_NAVCOLORBASIC
#DEFINE TESTING_NAVCURSORMOVEMENT
#DEFINE TESTING_NAVSCREENCLEARING
#DEFINE TESTING_NAVTEXTFORMATTING
#DEFINE TESTING_NAVCOLORRGB
#DEFINE TESTING_NAVUTILITYFUNCTIONS
#DEFINE TESTING_NAVUIELEMENTS
#DEFINE TESTING_NAVREPEATCHAR
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Tui.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVGETCOLOR
#include 'NAVGetColor.axi'
#END_IF

#IF_DEFINED TESTING_NAVCOLORBASIC
#include 'NAVColorBasic.axi'
#END_IF

#IF_DEFINED TESTING_NAVCURSORMOVEMENT
#include 'NAVCursorMovement.axi'
#END_IF

#IF_DEFINED TESTING_NAVSCREENCLEARING
#include 'NAVScreenClearing.axi'
#END_IF

#IF_DEFINED TESTING_NAVTEXTFORMATTING
#include 'NAVTextFormatting.axi'
#END_IF

#IF_DEFINED TESTING_NAVCOLORRGB
#include 'NAVColorRGB.axi'
#END_IF

#IF_DEFINED TESTING_NAVUTILITYFUNCTIONS
#include 'NAVUtilityFunctions.axi'
#END_IF

#IF_DEFINED TESTING_NAVUIELEMENTS
#include 'NAVUIElements.axi'
#END_IF

#IF_DEFINED TESTING_NAVREPEATCHAR
#include 'NAVRepeatChar.axi'
#END_IF


define_function RunTuiTests() {
    #IF_DEFINED TESTING_NAVGETCOLOR
    TestNAVGetColor()
    #END_IF

    #IF_DEFINED TESTING_NAVCOLORBASIC
    TestNAVColorBasic()
    #END_IF

    #IF_DEFINED TESTING_NAVCURSORMOVEMENT
    TestNAVCursorMovement()
    #END_IF

    #IF_DEFINED TESTING_NAVSCREENCLEARING
    TestNAVScreenClearing()
    #END_IF

    #IF_DEFINED TESTING_NAVTEXTFORMATTING
    TestNAVTextFormatting()
    #END_IF

    #IF_DEFINED TESTING_NAVCOLORRGB
    TestNAVColorRGB()
    #END_IF

    #IF_DEFINED TESTING_NAVUTILITYFUNCTIONS
    TestNAVUtilityFunctions()
    #END_IF

    #IF_DEFINED TESTING_NAVUIELEMENTS
    TestNAVUIElements()
    #END_IF

    #IF_DEFINED TESTING_NAVREPEATCHAR
    TestNAVRepeatChar()
    #END_IF
}
