#DEFINE TESTING_NAVREADDIRECTORY
#DEFINE TESTING_NAVFILEEXISTS
#DEFINE TESTING_NAVDIRECTORYEXISTS
#DEFINE TESTING_NAVWALKDIRECTORY
#DEFINE TESTING_NAVFILEWRITE
#DEFINE TESTING_NAVFILEREAD
#DEFINE TESTING_NAVFILEAPPEND
#DEFINE TESTING_NAVDIRECTORYCREATE
#DEFINE TESTING_NAVDIRECTORYDELETE
#DEFINE TESTING_NAVFILEDELETE
#DEFINE TESTING_NAVFILEGETSIZE
#DEFINE TESTING_NAVFILERENAME
#DEFINE TESTING_NAVFILECOPY
#DEFINE TESTING_NAVFILEREADLINE
#DEFINE TESTING_NAVFILEWRITELINE
#DEFINE TESTING_NAVFILEAPPENDLINE
#DEFINE TESTING_NAVGETFILEERROR
#DEFINE TESTING_NAVFILEOPENCLOSE
#DEFINE TESTING_NAVFILESEEK

#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.FileUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVFILEEXISTS
#include 'NAVFileExists.axi'
#END_IF

#IF_DEFINED TESTING_NAVDIRECTORYEXISTS
#include 'NAVDirectoryExists.axi'
#END_IF

#IF_DEFINED TESTING_NAVREADDIRECTORY
#include 'NAVReadDirectory.axi'
#END_IF

#IF_DEFINED TESTING_NAVWALKDIRECTORY
#include 'NAVWalkDirectory.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEWRITE
#include 'NAVFileWrite.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEREAD
#include 'NAVFileRead.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEAPPEND
#include 'NAVFileAppend.axi'
#END_IF

#IF_DEFINED TESTING_NAVDIRECTORYCREATE
#include 'NAVDirectoryCreate.axi'
#END_IF

#IF_DEFINED TESTING_NAVDIRECTORYDELETE
#include 'NAVDirectoryDelete.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEDELETE
#include 'NAVFileDelete.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEGETSIZE
#include 'NAVFileGetSize.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILERENAME
#include 'NAVFileRename.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILECOPY
#include 'NAVFileCopy.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEREADLINE
#include 'NAVFileReadLine.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEWRITELINE
#include 'NAVFileWriteLine.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEAPPENDLINE
#include 'NAVFileAppendLine.axi'
#END_IF

#IF_DEFINED TESTING_NAVGETFILEERROR
#include 'NAVGetFileError.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILEOPENCLOSE
#include 'NAVFileOpenClose.axi'
#END_IF

#IF_DEFINED TESTING_NAVFILESEEK
#include 'NAVFileSeek.axi'
#END_IF

define_function RunFileUtilsTests() {
    #IF_DEFINED TESTING_NAVREADDIRECTORY
    TestNAVReadDirectory()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEEXISTS
    TestNAVFileExists()
    #END_IF

    #IF_DEFINED TESTING_NAVDIRECTORYEXISTS
    TestNAVDirectoryExists()
    #END_IF

    #IF_DEFINED TESTING_NAVWALKDIRECTORY
    TestNAVWalkDirectory()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEWRITE
    TestNAVFileWrite()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEREAD
    TestNAVFileRead()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEAPPEND
    TestNAVFileAppend()
    #END_IF

    #IF_DEFINED TESTING_NAVDIRECTORYCREATE
    TestNAVDirectoryCreate()
    #END_IF

    #IF_DEFINED TESTING_NAVDIRECTORYDELETE
    TestNAVDirectoryDelete()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEDELETE
    TestNAVFileDelete()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEGETSIZE
    TestNAVFileGetSize()
    #END_IF

    #IF_DEFINED TESTING_NAVFILERENAME
    TestNAVFileRename()
    #END_IF

    #IF_DEFINED TESTING_NAVFILECOPY
    TestNAVFileCopy()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEREADLINE
    TestNAVFileReadLine()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEWRITELINE
    TestNAVFileWriteLine()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEAPPENDLINE
    TestNAVFileAppendLine()
    #END_IF

    #IF_DEFINED TESTING_NAVGETFILEERROR
    TestNAVGetFileError()
    #END_IF

    #IF_DEFINED TESTING_NAVFILEOPENCLOSE
    TestNAVFileOpenClose()
    #END_IF

    #IF_DEFINED TESTING_NAVFILESEEK
    TestNAVFileSeek()
    #END_IF
}
