#DEFINE TESTING_NAVWEBSOCKETISVALIDOPCODE
#DEFINE TESTING_NAVWEBSOCKETISCONTROLFRAME
#DEFINE TESTING_NAVWEBSOCKETISVALIDCLOSECODE
#DEFINE TESTING_NAVWEBSOCKETMASKDATA
#DEFINE TESTING_NAVWEBSOCKETBUILDTEXTFRAME
#DEFINE TESTING_NAVWEBSOCKETBUILDBINARYFRAME
#DEFINE TESTING_NAVWEBSOCKETBUILDCLOSEFRAME
#DEFINE TESTING_NAVWEBSOCKETBUILDPINGFRAME
#DEFINE TESTING_NAVWEBSOCKETBUILDPONGFRAME
#DEFINE TESTING_NAVWEBSOCKETGETFRAMELENGTH
#DEFINE TESTING_NAVWEBSOCKETPARSEFRAME
#DEFINE TESTING_NAVWEBSOCKETPARSECLOSEFRAME
#DEFINE TESTING_NAVWEBSOCKETBUILDHANDSHAKEREQUEST
#DEFINE TESTING_NAVWEBSOCKETVALIDATEHANDSHAKERESPONSE
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.WebSocket.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVWEBSOCKETISVALIDOPCODE
#include 'NAVWebSocketIsValidOpcode.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETISCONTROLFRAME
#include 'NAVWebSocketIsControlFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETISVALIDCLOSECODE
#include 'NAVWebSocketIsValidCloseCode.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETMASKDATA
#include 'NAVWebSocketMaskData.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETBUILDTEXTFRAME
#include 'NAVWebSocketBuildTextFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETBUILDBINARYFRAME
#include 'NAVWebSocketBuildBinaryFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETBUILDCLOSEFRAME
#include 'NAVWebSocketBuildCloseFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETBUILDPINGFRAME
#include 'NAVWebSocketBuildPingFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETBUILDPONGFRAME
#include 'NAVWebSocketBuildPongFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETGETFRAMELENGTH
#include 'NAVWebSocketGetFrameLength.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETPARSEFRAME
#include 'NAVWebSocketParseFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETPARSECLOSEFRAME
#include 'NAVWebSocketParseCloseFrame.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETBUILDHANDSHAKEREQUEST
#include 'NAVWebSocketBuildHandshakeRequest.axi'
#END_IF

#IF_DEFINED TESTING_NAVWEBSOCKETVALIDATEHANDSHAKERESPONSE
#include 'NAVWebSocketValidateHandshakeResponse.axi'
#END_IF


define_function RunWebSocketTests() {
    #IF_DEFINED TESTING_NAVWEBSOCKETISVALIDOPCODE
    TestNAVWebSocketIsValidOpcode()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETISCONTROLFRAME
    TestNAVWebSocketIsControlFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETISVALIDCLOSECODE
    TestNAVWebSocketIsValidCloseCode()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETMASKDATA
    TestNAVWebSocketMaskData()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETBUILDTEXTFRAME
    TestNAVWebSocketBuildTextFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETBUILDBINARYFRAME
    TestNAVWebSocketBuildBinaryFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETBUILDCLOSEFRAME
    TestNAVWebSocketBuildCloseFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETBUILDPINGFRAME
    TestNAVWebSocketBuildPingFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETBUILDPONGFRAME
    TestNAVWebSocketBuildPongFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETGETFRAMELENGTH
    TestNAVWebSocketGetFrameLength()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETPARSEFRAME
    TestNAVWebSocketParseFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETPARSECLOSEFRAME
    TestNAVWebSocketParseCloseFrame()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETBUILDHANDSHAKEREQUEST
    TestNAVWebSocketBuildHandshakeRequest()
    #END_IF

    #IF_DEFINED TESTING_NAVWEBSOCKETVALIDATEHANDSHAKERESPONSE
    TestNAVWebSocketValidateHandshakeResponse()
    #END_IF
}
