PROGRAM_NAME='queue-utils'

#DEFINE __MAIN__
#DEFINE TESTING_NAVQUEUE_INIT
#DEFINE TESTING_NAVQUEUE_ENQUEUE_DEQUEUE
#DEFINE TESTING_NAVQUEUE_EMPTY_FULL
#DEFINE TESTING_NAVQUEUE_HASITEMS
#DEFINE TESTING_NAVQUEUE_COUNT_CAPACITY
#DEFINE TESTING_NAVQUEUE_PEEK
#DEFINE TESTING_NAVQUEUE_CLEAR
#DEFINE TESTING_NAVQUEUE_CONTAINS
#DEFINE TESTING_NAVQUEUE_TOSTRING
#DEFINE TESTING_NAVQUEUE_WRAPPING
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVQUEUE_INIT
#include 'NAVQueueInit.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_ENQUEUE_DEQUEUE
#include 'NAVQueueEnqueueDequeue.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_EMPTY_FULL
#include 'NAVQueueEmptyFull.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_HASITEMS
#include 'NAVQueueHasItems.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_COUNT_CAPACITY
#include 'NAVQueueCountCapacity.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_PEEK
#include 'NAVQueuePeek.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_CLEAR
#include 'NAVQueueClear.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_CONTAINS
#include 'NAVQueueContains.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_TOSTRING
#include 'NAVQueueToString.axi'
#END_IF

#IF_DEFINED TESTING_NAVQUEUE_WRAPPING
#include 'NAVQueueWrapping.axi'
#END_IF


DEFINE_DEVICE

dvTP    =   10001:1:0


define_function RunTests() {
    #IF_DEFINED TESTING_NAVQUEUE_INIT
    TestNAVQueueInit()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_ENQUEUE_DEQUEUE
    TestNAVQueueEnqueueDequeue()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_EMPTY_FULL
    TestNAVQueueEmptyFull()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_HASITEMS
    TestNAVQueueHasItems()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_COUNT_CAPACITY
    TestNAVQueueCountCapacity()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_PEEK
    TestNAVQueuePeek()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_CLEAR
    TestNAVQueueClear()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_CONTAINS
    TestNAVQueueContains()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_TOSTRING
    TestNAVQueueToString()
    #END_IF

    #IF_DEFINED TESTING_NAVQUEUE_WRAPPING
    TestNAVQueueWrapping()
    #END_IF
}


DEFINE_EVENT

button_event[dvTP, 1] {
    push: {
        RunTests()
    }
}
