#DEFINE TESTING_NAVBASE64URLENCODE
#DEFINE TESTING_NAVBASE64URLENCODEPADDED
#DEFINE TESTING_NAVBASE64URLDECODE
#DEFINE TESTING_NAVBASE64TOBASE64URL
#DEFINE TESTING_NAVBASE64URLTOBASE64
#DEFINE TESTING_NAVBASE64URLROUNDTRIP
#DEFINE TESTING_NAVBASE64URLWHITESPACE
#DEFINE TESTING_NAVBASE64URLERRORHANDLING
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.Encoding.Base64Url.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.Testing.axi'
#include 'NAVBase64UrlShared.axi'

#IF_DEFINED TESTING_NAVBASE64URLENCODE
#include 'NAVBase64UrlEncode.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64URLENCODEPADDED
#include 'NAVBase64UrlEncodePadded.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64URLDECODE
#include 'NAVBase64UrlDecode.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64TOBASE64URL
#include 'NAVBase64ToBase64Url.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64URLTOBASE64
#include 'NAVBase64UrlToBase64.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64URLROUNDTRIP
#include 'NAVBase64UrlRoundTrip.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64URLWHITESPACE
#include 'NAVBase64UrlWhitespace.axi'
#END_IF

#IF_DEFINED TESTING_NAVBASE64URLERRORHANDLING
#include 'NAVBase64UrlErrorHandling.axi'
#END_IF

define_function RunBase64UrlTests() {
    #IF_DEFINED TESTING_NAVBASE64URLENCODE
    TestNAVBase64UrlEncode()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64URLENCODEPADDED
    TestNAVBase64UrlEncodePadded()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64URLDECODE
    TestNAVBase64UrlDecode()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64TOBASE64URL
    TestNAVBase64ToBase64Url()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64URLTOBASE64
    TestNAVBase64UrlToBase64()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64URLROUNDTRIP
    TestNAVBase64UrlRoundTrip()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64URLWHITESPACE
    TestNAVBase64UrlWhitespace()
    #END_IF

    #IF_DEFINED TESTING_NAVBASE64URLERRORHANDLING
    TestNAVBase64UrlErrorHandling()
    #END_IF
}
