#DEFINE TESTING_NAVHTTPREQUESTINIT
#DEFINE TESTING_NAVHTTPBUILDREQUEST
#DEFINE TESTING_NAVHTTPREQUESTHEADERS
#DEFINE TESTING_NAVHTTPRESPONSEPARSE
#DEFINE TESTING_NAVHTTPBUILDRESPONSE
#DEFINE TESTING_NAVHTTPINFERCONTENTTYPE
#DEFINE TESTING_NAVHTTPGETSTATUSMESSAGE
#DEFINE TESTING_NAVHTTPRESPONSEMAYHAVEBODY
#DEFINE TESTING_NAVHTTPGETDEFAULTPORT
#DEFINE TESTING_NAVHTTPVALIDATEHEADERS
#DEFINE TESTING_NAVHTTPPARSERESPONSEBODY
#DEFINE TESTING_NAVHTTPPARSEURL
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.HttpUtils.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'
#include 'NAVHttpTestShared.axi'

#IF_DEFINED TESTING_NAVHTTPREQUESTINIT
#include 'NAVHttpRequestInit.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPBUILDREQUEST
#include 'NAVHttpBuildRequest.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPREQUESTHEADERS
#include 'NAVHttpRequestHeaders.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPRESPONSEPARSE
#include 'NAVHttpResponseParse.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPBUILDRESPONSE
#include 'NAVHttpBuildResponse.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPINFERCONTENTTYPE
#include 'NAVHttpInferContentType.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPGETSTATUSMESSAGE
#include 'NAVHttpGetStatusMessage.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPRESPONSEMAYHAVEBODY
#include 'NAVHttpResponseMayHaveBody.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPGETDEFAULTPORT
#include 'NAVHttpGetDefaultPort.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPVALIDATEHEADERS
#include 'NAVHttpValidateHeaders.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPPARSERESPONSEBODY
#include 'NAVHttpParseResponseBody.axi'
#END_IF

#IF_DEFINED TESTING_NAVHTTPPARSEURL
#include 'NAVHttpParseUrl.axi'
#END_IF

define_function RunHttpUtilsTests() {
    #IF_DEFINED TESTING_NAVHTTPREQUESTINIT
    TestNAVHttpRequestInit()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPBUILDREQUEST
    TestNAVHttpBuildRequest()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPREQUESTHEADERS
    TestNAVHttpRequestAddHeader()
    TestNAVHttpRequestUpdateHeader()
    TestNAVHttpHeaderHelpers()
    TestNAVHttpResponseAddHeader()
    TestNAVHttpResponseUpdateHeader()
    TestNAVHttpHeaderEdgeCases()
    TestNAVHttpHeaderValidation()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPRESPONSEPARSE
    TestNAVHttpParseResponse()
    TestNAVHttpParseStatusLine()
    TestNAVHttpParseHeaders()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPBUILDRESPONSE
    TestNAVHttpBuildResponse()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPINFERCONTENTTYPE
    TestNAVHttpInferContentType()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPGETSTATUSMESSAGE
    TestNAVHttpGetStatusMessage()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPRESPONSEMAYHAVEBODY
    TestNAVHttpResponseMayHaveBody()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPGETDEFAULTPORT
    TestNAVHttpGetDefaultPort()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPVALIDATEHEADERS
    TestNAVHttpValidateHeaders()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPPARSERESPONSEBODY
    TestNAVHttpParseResponseBody()
    #END_IF

    #IF_DEFINED TESTING_NAVHTTPPARSEURL
    TestNAVHttpParseUrl()
    #END_IF
}
