#DEFINE TESTING_NAVBINARYROTATELEFT
#DEFINE TESTING_NAVBINARYROTATERIGHT
#DEFINE TESTING_NAVBITROTATELEFT
#DEFINE TESTING_NAVBITROTATERIGHT
#DEFINE TESTING_NAVBINARYGETBIT
#DEFINE TESTING_NAVBYTETOBITARRAY
#DEFINE TESTING_NAVBYTETOBINARYSTRING
#DEFINE TESTING_NAVBCDTOBINARY
#DEFINE TESTING_NAVBINARYTOBCD

#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.BinaryUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVBINARYROTATELEFT
#include 'NAVBinaryRotateLeft.axi'
#END_IF

#IF_DEFINED TESTING_NAVBINARYROTATERIGHT
#include 'NAVBinaryRotateRight.axi'
#END_IF

#IF_DEFINED TESTING_NAVBITROTATELEFT
#include 'NAVBitRotateLeft.axi'
#END_IF

#IF_DEFINED TESTING_NAVBITROTATERIGHT
#include 'NAVBitRotateRight.axi'
#END_IF

#IF_DEFINED TESTING_NAVBINARYGETBIT
#include 'NAVBinaryGetBit.axi'
#END_IF

#IF_DEFINED TESTING_NAVBYTETOBITARRAY
#include 'NAVByteToBitArray.axi'
#END_IF

#IF_DEFINED TESTING_NAVBYTETOBINARYSTRING
#include 'NAVByteToBinaryString.axi'
#END_IF

#IF_DEFINED TESTING_NAVBCDTOBINARY
#include 'NAVBcdToBinary.axi'
#END_IF

#IF_DEFINED TESTING_NAVBINARYTOBCD
#include 'NAVBinaryToBcd.axi'
#END_IF

define_function RunBinaryUtilsTests() {
    #IF_DEFINED TESTING_NAVBINARYROTATELEFT
    TestNAVBinaryRotateLeft()
    #END_IF

    #IF_DEFINED TESTING_NAVBINARYROTATERIGHT
    TestNAVBinaryRotateRight()
    #END_IF

    #IF_DEFINED TESTING_NAVBITROTATELEFT
    TestNAVBitRotateLeft()
    #END_IF

    #IF_DEFINED TESTING_NAVBITROTATERIGHT
    TestNAVBitRotateRight()
    #END_IF

    #IF_DEFINED TESTING_NAVBINARYGETBIT
    TestNAVBinaryGetBit()
    #END_IF

    #IF_DEFINED TESTING_NAVBYTETOBITARRAY
    TestNAVByteToBitArray()
    #END_IF

    #IF_DEFINED TESTING_NAVBYTETOBINARYSTRING
    TestNAVByteToBinaryString()
    #END_IF

    #IF_DEFINED TESTING_NAVBCDTOBINARY
    TestNAVBcdToBinary()
    #END_IF

    #IF_DEFINED TESTING_NAVBINARYTOBCD
    TestNAVBinaryToBcd()
    #END_IF
}
