#DEFINE TESTING_NAVNETPARSEIPV4
#DEFINE TESTING_NAVNETSPLITHOSTPORT
#DEFINE TESTING_NAVNETPARSEIPADDR
#DEFINE TESTING_NAVNETJOINHOSTPORT
#DEFINE TESTING_NAVNETPARSEHOSTNAME
#DEFINE TESTING_NAVNETISMALFORMEDIP
#DEFINE TESTING_NAVNETSUBNETMASKTOPREFIX
#DEFINE TESTING_NAVNETPREFIXTOSUBNETMASK
#DEFINE TESTING_NAVNETIPTOLONG
#DEFINE TESTING_NAVNETLONGTOIP
#DEFINE TESTING_NAVNETCALCULATEBROADCAST
#DEFINE TESTING_NAVNETCALCULATENETWORKADDRESS
#DEFINE TESTING_NAVNETCALCULATEHOSTCOUNT
#DEFINE TESTING_NAVNETISINSUBNET
#DEFINE TESTING_NAVNETISPRIVATEIP
#DEFINE TESTING_NAVNETISLOOPBACK
#DEFINE TESTING_NAVNETISLINKLOCAL
#DEFINE TESTING_NAVNETISMULTICAST
#include 'NAVFoundation.Core.axi'
#include 'NAVFoundation.NetUtils.axi'
#include 'NAVFoundation.Assert.axi'
#include 'NAVFoundation.ErrorLogUtils.axi'
#include 'NAVFoundation.Testing.axi'

#IF_DEFINED TESTING_NAVNETPARSEIPV4
#include 'NAVNetParseIPv4.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETSPLITHOSTPORT
#include 'NAVNetSplitHostPort.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETPARSEIPADDR
#include 'NAVNetParseIPAddr.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETJOINHOSTPORT
#include 'NAVNetJoinHostPort.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETPARSEHOSTNAME
#include 'NAVNetParseHostname.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETISMALFORMEDIP
#include 'NAVNetIsMalformedIP.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETSUBNETMASKTOPREFIX
#include 'NAVNetSubnetMaskToPrefix.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETPREFIXTOSUBNETMASK
#include 'NAVNetPrefixToSubnetMask.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETIPTOLONG
#include 'NAVNetIPToLong.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETLONGTOIP
#include 'NAVNetLongToIP.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETCALCULATEBROADCAST
#include 'NAVNetCalculateBroadcast.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETCALCULATENETWORKADDRESS
#include 'NAVNetCalculateNetworkAddress.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETCALCULATEHOSTCOUNT
#include 'NAVNetCalculateHostCount.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETISINSUBNET
#include 'NAVNetIsIPInSubnet.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETISPRIVATEIP
#include 'NAVNetIsPrivateIP.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETISLOOPBACK
#include 'NAVNetIsLoopback.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETISLINKLOCAL
#include 'NAVNetIsLinkLocal.axi'
#END_IF

#IF_DEFINED TESTING_NAVNETISMULTICAST
#include 'NAVNetIsMulticast.axi'
#END_IF

define_function RunNetUtilsTests() {
    #IF_DEFINED TESTING_NAVNETPARSEIPV4
    TestNAVNetParseIPv4()
    #END_IF

    #IF_DEFINED TESTING_NAVNETSPLITHOSTPORT
    TestNAVNetSplitHostPort()
    #END_IF

    #IF_DEFINED TESTING_NAVNETPARSEIPADDR
    TestNAVNetParseIPAddr()
    #END_IF

    #IF_DEFINED TESTING_NAVNETJOINHOSTPORT
    TestNAVNetJoinHostPort()
    #END_IF

    #IF_DEFINED TESTING_NAVNETPARSEHOSTNAME
    TestNAVNetParseHostname()
    #END_IF

    #IF_DEFINED TESTING_NAVNETISMALFORMEDIP
    TestNAVNetIsMalformedIP()
    #END_IF

    #IF_DEFINED TESTING_NAVNETSUBNETMASKTOPREFIX
    TestNAVNetSubnetMaskToPrefix()
    #END_IF

    #IF_DEFINED TESTING_NAVNETPREFIXTOSUBNETMASK
    TestNAVNetPrefixToSubnetMask()
    #END_IF

    #IF_DEFINED TESTING_NAVNETIPTOLONG
    TestNAVNetIPToLong()
    #END_IF

    #IF_DEFINED TESTING_NAVNETLONGTOIP
    TestNAVNetLongToIP()
    #END_IF

    #IF_DEFINED TESTING_NAVNETCALCULATEBROADCAST
    TestNAVNetCalculateBroadcast()
    TestNAVNetCalculateBroadcastFromPrefix()
    #END_IF

    #IF_DEFINED TESTING_NAVNETCALCULATENETWORKADDRESS
    TestNAVNetCalculateNetworkAddress()
    TestNAVNetCalculateNetworkAddressFromPrefix()
    #END_IF

    #IF_DEFINED TESTING_NAVNETCALCULATEHOSTCOUNT
    TestNAVNetCalculateHostCount()
    #END_IF

    #IF_DEFINED TESTING_NAVNETISINSUBNET
    TestNAVNetIsIPInSubnet()
    TestNAVNetIsIPInSubnetFromPrefix()
    #END_IF

    #IF_DEFINED TESTING_NAVNETISPRIVATEIP
    TestNAVNetIsPrivateIP()
    #END_IF

    #IF_DEFINED TESTING_NAVNETISLOOPBACK
    TestNAVNetIsLoopback()
    #END_IF

    #IF_DEFINED TESTING_NAVNETISLINKLOCAL
    TestNAVNetIsLinkLocal()
    #END_IF

    #IF_DEFINED TESTING_NAVNETISMULTICAST
    TestNAVNetIsMulticast()
    #END_IF
}
