name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ["self-hosted", "windows", "server"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Show Environment
        run: |
          $PSVersionTable
          $pwd
          whoami

      - name: Check genlinx
        run: which genlinx

      - name: Run genlinx
        run: genlinx build -c NAVFoundation.ci.build.cfg

      - name: Upload build log only if failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-log
          path: ./*.build.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./**/*.tkn
            ./**/*.tko
            ./*.build.log
